import pathlib
import json
from cassandra.cluster import Cluster
from cassandra.auth import PlainTextAuthProvider
from cassandra.cqlengine import connection
from app import config


# This secure connect bundle is autogenerated when you donwload your SCB,
# if yours is different update the file name below
settings = config.get_settings()

BASE_DIR = pathlib.Path(__file__).resolve().parent

ASTRA_CONNECT_BUNDLE = BASE_DIR / "unencrypted" / "astradb_connect.zip"
ASTRA_CLIENT_ID = settings.astra_client_id
ASTRA_CLIENT_SECRET = settings.astra_client_secret

def get_session():
    cloud_config = {
        'secure_connect_bundle': ASTRA_CONNECT_BUNDLE
    }

    CLIENT_ID =   ASTRA_CLIENT_ID
    CLIENT_SECRET =  ASTRA_CLIENT_SECRET

    auth_provider = PlainTextAuthProvider(CLIENT_ID, CLIENT_SECRET)
    cluster = Cluster(cloud=cloud_config, auth_provider=auth_provider)
    session = cluster.connect()
    connection.register_connection(str(session), session=session)
    connection.set_default_connection(str(session))
    return session


    # This token json file is autogenerated when you donwload your token,
    # if yours is different update the file name below
    # with open("igwemiraclenzube@gmail.com-token.json") as f:
    #     secrets = json.load(f)